  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_xy
      - joint_zx
      - joint_needle
      - joint_2_x
      - joint_2_z
      - joint_3_x
      - joint_3_z
      - joint_4_x
      - joint_4_z
      - joint_5_x
      - joint_5_z
    
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity








 



















